In [1]:
import numpy as np
from grabscreen import grab_screen
import cv2
import time
from directkeys import PressKey,ReleaseKey, W, A, S, D
from alexnet import alexnet
from getkeys import key_check

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
import random

WIDTH = 160
HEIGHT = 120
LR = 1e-3
EPOCHS = 10
MODEL_NAME = 'pynfs5-car-fast-{}-{}-{}-epochs-2K-data.model'.format(LR, 'alexnetv2',EPOCHS)
#MODEL_NAME = 'pynfs5-car-fast-0.001-alexnetv2-10-epochs-2K-data.model'

In [3]:
t_time = 0.09

def straight():
##    if random.randrange(4) == 2:
##        ReleaseKey(W)
##    else:
    PressKey(W)
    ReleaseKey(A)
    ReleaseKey(D)

def left():
    PressKey(W)
    PressKey(A)
    #ReleaseKey(W)
    ReleaseKey(D)
    #ReleaseKey(A)
    time.sleep(t_time)
    ReleaseKey(A)

def right():
    PressKey(W)
    PressKey(D)
    ReleaseKey(A)
    #ReleaseKey(W)
    #ReleaseKey(D)
    time.sleep(t_time)
    ReleaseKey(D)

In [4]:
model = alexnet(WIDTH, HEIGHT, LR)
model.load(MODEL_NAME)

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
INFO:tensorflow:Restoring parameters from C:\Users\user\Desktop\Semester - 6\Swamchalak Vahan\PROJECT\neural caar\pynfs5-car-fast-0.001-alexnetv2-10-epochs-2K-data.model


In [5]:
def main():
    last_time = time.time()
    for i in list(range(4))[::-1]:
        print(i+1)
        time.sleep(1)

    paused = False
    while(True):
        
        if not paused:
            # 800x600 windowed mode
            #screen =  np.array(ImageGrab.grab(bbox=(0,40,800,640)))
            screen = grab_screen(region=(120,120,730,580))
            print('loop took {} seconds'.format(time.time()-last_time))
            last_time = time.time()
            screen = cv2.cvtColor(screen, cv2.COLOR_BGR2GRAY)
            screen = cv2.resize(screen, (160,120))

            prediction = model.predict([screen.reshape(160,120,1)])[0]
            print(prediction)

            turn_thresh = .75
            fwd_thresh = 0.70

            if prediction[1] > fwd_thresh:
                straight()
            elif prediction[0] > turn_thresh:
                left()
            elif prediction[2] > turn_thresh:
                right()
            else:
                straight()

        keys = key_check()

        # p pauses game and can get annoying.
        if 'T' in keys:
            if paused:
                paused = False
                time.sleep(1)
            else:
                paused = True
                ReleaseKey(A)
                ReleaseKey(W)
                ReleaseKey(D)
                time.sleep(1)

In [ ]:
main()

4
3
2
1
loop took 7.093451738357544 seconds
[0.7012821  0.01416474 0.28455317]
loop took 15.60693907737732 seconds
[0.8403352  0.01146399 0.14820082]
loop took 0.3208785057067871 seconds
[0.78594303 0.0166253  0.19743164]
loop took 0.6227548122406006 seconds
[0.6426269  0.04245014 0.31492296]
loop took 0.11892223358154297 seconds
[0.68057835 0.03084101 0.28858063]
loop took 0.16841959953308105 seconds
[0.8037107  0.03147209 0.16481726]
loop took 0.19552135467529297 seconds
[0.7869201  0.05293901 0.16014098]
loop took 0.18640613555908203 seconds
[0.86097246 0.0192533  0.11977428]
loop took 0.26802706718444824 seconds
[0.8906597  0.01007144 0.09926891]
loop took 0.21494555473327637 seconds
[0.934645   0.01286732 0.05248774]
loop took 0.277393102645874 seconds
[0.963951   0.0071084  0.02894057]
loop took 0.20232915878295898 seconds
[0.9748583  0.00149721 0.02364456]
loop took 0.23402762413024902 seconds
[0.9774574  0.00368096 0.01886168]
loop took 0.24037671089172363 seconds
[9.9687374e-0

loop took 0.18089747428894043 seconds
[0.2919651  0.59953815 0.10849676]
loop took 0.12801265716552734 seconds
[0.4762113  0.14291996 0.3808687 ]
loop took 0.10993671417236328 seconds
[0.6542995  0.24500892 0.10069159]
loop took 0.13891959190368652 seconds
[0.09767617 0.8571703  0.04515355]
loop took 0.10993790626525879 seconds
[0.03629033 0.95085907 0.01285058]
loop took 0.1274418830871582 seconds
[0.02026703 0.96650475 0.01322816]
loop took 0.0677037239074707 seconds
[0.02026703 0.96650475 0.01322816]
loop took 0.14843487739562988 seconds
[2.2773773e-03 9.9679345e-01 9.2920085e-04]
loop took 0.21742582321166992 seconds
[0.10918149 0.8888441  0.00197442]
loop took 0.14102911949157715 seconds
[0.974921   0.02143212 0.00364702]
loop took 0.2557239532470703 seconds
[9.9683493e-01 7.5446058e-04 2.4106535e-03]
loop took 0.23287463188171387 seconds
[9.9745661e-01 6.0706137e-04 1.9363307e-03]
loop took 0.21319842338562012 seconds
[9.9759066e-01 1.5345335e-03 8.7479333e-04]
loop took 0.235346

loop took 0.21894121170043945 seconds
[9.9371827e-01 7.1777886e-04 5.5639581e-03]
loop took 0.2254316806793213 seconds
[9.9745828e-01 4.3906894e-04 2.1026365e-03]
loop took 0.21090102195739746 seconds
[9.9643022e-01 5.2490551e-04 3.0448858e-03]
loop took 0.22390174865722656 seconds
[0.24881764 0.00263334 0.74854904]
loop took 0.15191292762756348 seconds
[2.7584811e-03 7.0184196e-04 9.9653971e-01]
loop took 0.2476952075958252 seconds
[2.7440277e-05 1.5431440e-04 9.9981827e-01]
loop took 0.24846267700195312 seconds
[2.8038054e-04 6.8956940e-04 9.9903011e-01]
loop took 0.2151188850402832 seconds
[0.66040987 0.02495611 0.31463403]
loop took 0.1359260082244873 seconds
[0.95056957 0.01775557 0.03167484]
loop took 0.19692206382751465 seconds
[0.99305665 0.00325981 0.00368355]
loop took 0.2048053741455078 seconds
[0.9899852  0.00520781 0.00480701]
loop took 0.2268965244293213 seconds
[0.99375135 0.00136312 0.00488548]
loop took 0.21787548065185547 seconds
[9.9412483e-01 4.7478377e-04 5.4004490

loop took 0.1954174041748047 seconds
[0.4760809  0.01279688 0.5111222 ]
loop took 0.15191960334777832 seconds
[0.3336751  0.01641119 0.6499137 ]
loop took 0.21430611610412598 seconds
[0.19471587 0.00867665 0.7966075 ]
loop took 0.23038077354431152 seconds
[0.64804745 0.00300848 0.3489441 ]
loop took 0.14291906356811523 seconds
[0.6685793  0.00293523 0.32848555]
loop took 0.13243651390075684 seconds
[0.7819087  0.00152867 0.21656269]
loop took 0.2988927364349365 seconds
[0.92147166 0.00204841 0.07647987]
loop took 0.2694566249847412 seconds
[0.36850277 0.00281306 0.6286842 ]
loop took 0.16090893745422363 seconds
[0.28617707 0.00418458 0.70963836]
loop took 0.1916353702545166 seconds
[6.3156635e-02 7.1449002e-04 9.3612891e-01]
loop took 0.22339606285095215 seconds
[0.26858178 0.00208165 0.72933656]
loop took 0.10993647575378418 seconds
[0.2630681  0.00122028 0.73571163]
loop took 0.12193083763122559 seconds
[0.52628875 0.00100905 0.47270218]
loop took 0.16790342330932617 seconds
[0.69228

loop took 0.20795702934265137 seconds
[0.00414815 0.00805657 0.98779523]
loop took 0.21806788444519043 seconds
[0.00894291 0.06984477 0.9212123 ]
loop took 0.2634408473968506 seconds
[0.77591115 0.01711381 0.20697512]
loop took 0.2299485206604004 seconds
[0.9915692  0.00135867 0.00707217]
loop took 0.24809503555297852 seconds
[9.9180073e-01 6.0878927e-04 7.5905244e-03]
loop took 0.2524375915527344 seconds
[0.96760154 0.00336286 0.0290356 ]
loop took 0.21619200706481934 seconds
[0.10890712 0.01494566 0.87614715]
loop took 0.20583295822143555 seconds
[0.00815134 0.0153671  0.9764815 ]
loop took 0.21687531471252441 seconds
[0.01594649 0.1330118  0.8510417 ]
loop took 0.23337912559509277 seconds
[0.05013547 0.1496132  0.8002513 ]
loop took 0.22787690162658691 seconds
[0.5368732  0.03612674 0.427     ]
loop took 0.16790366172790527 seconds
[0.8817879  0.08469764 0.03351445]
loop took 0.24744153022766113 seconds
[0.925169   0.06243542 0.0123956 ]
loop took 0.22786974906921387 seconds
[0.6942

loop took 0.23110318183898926 seconds
[0.08796281 0.00345147 0.9085858 ]
loop took 0.1948237419128418 seconds
[0.09528399 0.00809989 0.89661616]
loop took 0.2232074737548828 seconds
[0.26770535 0.0184137  0.71388096]
loop took 0.1249382495880127 seconds
[0.30584922 0.07787249 0.61627835]
loop took 0.13043928146362305 seconds
[0.26425862 0.06090009 0.6748413 ]
loop took 0.11896228790283203 seconds
[0.2142614  0.21637437 0.56936425]
loop took 0.11593341827392578 seconds
[0.2793219  0.12288039 0.59779775]
loop took 0.13592195510864258 seconds
[0.2846379  0.03624262 0.6791195 ]
loop took 0.17445135116577148 seconds
[0.251932   0.00981996 0.73824805]
loop took 0.13251972198486328 seconds
[0.11403641 0.0024484  0.8835152 ]
loop took 0.20088720321655273 seconds
[0.4673821  0.02145994 0.51115793]
loop took 0.09492802619934082 seconds
[0.0532638  0.01338178 0.93335444]
loop took 0.21429729461669922 seconds
[0.09500988 0.01325709 0.8917331 ]
loop took 0.23661088943481445 seconds
[0.04696972 0.13

[0.9731549  0.01723422 0.00961087]
loop took 0.19233012199401855 seconds
[0.8764497  0.10144853 0.02210181]
loop took 0.20068359375 seconds
[0.9864797  0.00757217 0.0059481 ]
loop took 0.2372584342956543 seconds
[0.9916626  0.00633248 0.00200496]
loop took 0.22986865043640137 seconds
[0.32775545 0.01999654 0.6522481 ]
loop took 0.11394906044006348 seconds
[0.03141608 0.002215   0.9663689 ]
loop took 0.20094656944274902 seconds
[0.02408065 0.0096295  0.9662899 ]
loop took 0.19655871391296387 seconds
[0.0531498 0.2969115 0.6499387]
loop took 0.1339247226715088 seconds
[0.2328476 0.5302355 0.2369169]
loop took 0.11755967140197754 seconds
[0.35318667 0.48027253 0.16654082]
loop took 0.11447739601135254 seconds
[0.5619365  0.36946508 0.06859838]
loop took 0.12293004989624023 seconds
[0.81490004 0.14769438 0.03740555]
loop took 0.1920762062072754 seconds
[0.96021116 0.01362687 0.02616198]
loop took 0.19751763343811035 seconds
[0.9450226  0.03808614 0.01689137]
loop took 0.22733712196350098 s

loop took 0.196030855178833 seconds
[0.0067855  0.00726049 0.985954  ]
loop took 0.22454619407653809 seconds
[6.1604480e-04 1.5274121e-03 9.9785656e-01]
loop took 0.24568986892700195 seconds
[4.2344496e-04 1.0131992e-03 9.9856335e-01]
loop took 0.2259349822998047 seconds
[3.4073106e-04 2.5476962e-03 9.9711156e-01]
loop took 0.2470102310180664 seconds
[6.0255959e-04 1.6836137e-02 9.8256129e-01]
loop took 0.24101591110229492 seconds
[0.00110555 0.06158939 0.93730503]
loop took 0.22330570220947266 seconds
[0.01209858 0.47593284 0.51196855]
loop took 0.15060925483703613 seconds
[0.51850545 0.38049823 0.10099628]
loop took 0.13917994499206543 seconds
[0.9674491  0.02452012 0.00803086]
loop took 0.25971007347106934 seconds
[9.9179149e-01 7.4176937e-03 7.9085288e-04]
loop took 0.21105742454528809 seconds
[0.9785454  0.01948564 0.00196896]
loop took 0.20064139366149902 seconds
[0.62106615 0.13520353 0.24373037]
loop took 0.11393547058105469 seconds
[0.01698675 0.10415759 0.8788557 ]
loop took 

loop took 0.16916799545288086 seconds
[0.7193944  0.22888751 0.05171809]
loop took 0.2680380344390869 seconds
[0.81138283 0.12533693 0.06328023]
loop took 0.23225164413452148 seconds
[0.9346531  0.05899019 0.00635674]
loop took 0.21717453002929688 seconds
[0.46328598 0.47628236 0.06043159]
loop took 0.13492393493652344 seconds
[0.18708852 0.23309097 0.5798205 ]
loop took 0.17580747604370117 seconds
[0.04245631 0.01745168 0.94009197]
loop took 0.25084590911865234 seconds
[0.02823785 0.00625159 0.9655106 ]
loop took 0.2544114589691162 seconds
[0.11471804 0.02909927 0.85618263]
loop took 0.25920867919921875 seconds
[0.9404089  0.04686427 0.01272684]
loop took 0.29352402687072754 seconds
[0.964224   0.01665904 0.01911696]
loop took 0.2658975124359131 seconds
[0.9924746  0.00306692 0.00445848]
loop took 0.21991539001464844 seconds
[0.98359525 0.01101088 0.0053939 ]
loop took 0.2316124439239502 seconds
[0.96118915 0.01371536 0.02509556]
loop took 0.1997060775756836 seconds
[0.2075063  0.0365

loop took 0.24780702590942383 seconds
[0.08220302 0.00343453 0.91436243]
loop took 0.2621634006500244 seconds
[0.2853794  0.00716698 0.70745355]
loop took 0.15235638618469238 seconds
[0.07212757 0.00575718 0.92211527]
loop took 0.2546713352203369 seconds
[0.12942508 0.00663851 0.86393636]
loop took 0.22435283660888672 seconds
[0.12915386 0.00436595 0.86648023]
loop took 0.21693801879882812 seconds
[0.14335296 0.00488109 0.85176593]
loop took 0.21561861038208008 seconds
[0.29316813 0.01952334 0.6873085 ]
loop took 0.13326382637023926 seconds
[0.45089492 0.0124637  0.53664136]
loop took 0.13245844841003418 seconds
[0.61072224 0.00281592 0.38646194]
loop took 0.13492202758789062 seconds
[0.56044984 0.00161293 0.4379372 ]
loop took 0.11447620391845703 seconds
[0.21578906 0.00194582 0.7822652 ]
loop took 0.20995736122131348 seconds
[0.5772009 0.001839  0.4209601]
loop took 0.08496642112731934 seconds
[0.5772009 0.001839  0.4209601]
loop took 0.06649541854858398 seconds
[0.5772009 0.001839  

[0.2625841  0.0075019  0.72991407]
loop took 0.16090774536132812 seconds
[0.7404508  0.00269023 0.25685892]
loop took 0.17404437065124512 seconds
[0.6186124  0.00472354 0.3766641 ]
loop took 0.1559140682220459 seconds
[0.43220595 0.00553937 0.56225467]
loop took 0.13292741775512695 seconds
[0.5908945  0.01022232 0.3988832 ]
loop took 0.12892436981201172 seconds
[0.44136274 0.01325992 0.5453773 ]
loop took 0.16489887237548828 seconds
[0.4332425  0.01489649 0.551861  ]
loop took 0.1685025691986084 seconds
[0.5073104  0.03575682 0.45693278]
loop took 0.16244864463806152 seconds
[0.6827934  0.03964229 0.2775644 ]
loop took 0.16190743446350098 seconds
[0.26257914 0.00931438 0.7281065 ]
loop took 0.11393427848815918 seconds
[0.03559133 0.00499077 0.9594179 ]
loop took 0.26093435287475586 seconds
[1.0876751e-02 2.3616770e-04 9.8888701e-01]
loop took 0.22887778282165527 seconds
[2.0230267e-02 9.5935812e-04 9.7881031e-01]
loop took 0.24158263206481934 seconds
[2.9654747e-03 2.1753306e-04 9.9681

[9.9536610e-01 3.9151926e-03 7.1874971e-04]
loop took 0.2540395259857178 seconds
[9.9770689e-01 5.7725713e-04 1.7157199e-03]
loop took 0.22682428359985352 seconds
[9.9923980e-01 3.6130627e-04 3.9894262e-04]
loop took 0.2320854663848877 seconds
[0.99255824 0.00106663 0.00637505]
loop took 0.19870638847351074 seconds
[0.50369483 0.05435991 0.4419453 ]
loop took 0.11993145942687988 seconds
[0.04424739 0.05599011 0.8997625 ]
loop took 0.23375272750854492 seconds
[0.0028355  0.00991425 0.9872502 ]
loop took 0.20345830917358398 seconds
[0.00496435 0.03759913 0.95743656]
loop took 0.22041964530944824 seconds
[0.01772617 0.15500894 0.82726485]
loop took 23.332857131958008 seconds
[0.97462046 0.00590441 0.01947513]
loop took 0.21767449378967285 seconds
[0.9721173  0.0080032  0.01987959]
loop took 0.21990299224853516 seconds
[0.9462455  0.01169994 0.04205457]
loop took 0.2359001636505127 seconds
[0.9416532  0.01932654 0.0390203 ]
loop took 0.23924660682678223 seconds
[0.9518632  0.01992168 0.028

[0.05628747 0.11416876 0.82954377]
loop took 0.3141610622406006 seconds
[0.69442105 0.0811349  0.22444397]
loop took 0.10094213485717773 seconds
[0.911177   0.01406171 0.0747613 ]
loop took 0.2029402256011963 seconds
[0.9772341  0.00581666 0.01694928]
loop took 0.2430734634399414 seconds
[0.94164574 0.00839373 0.04996049]
loop took 0.23821210861206055 seconds
[0.37267023 0.16960917 0.45772067]
loop took 0.1378006935119629 seconds
[0.05896089 0.22451226 0.71652687]
loop took 0.14891576766967773 seconds
[0.03131394 0.13501069 0.8336753 ]
loop took 0.2004106044769287 seconds
[0.01562054 0.09590522 0.8884743 ]
loop took 0.2326960563659668 seconds
[0.25279486 0.1828532  0.5643519 ]
loop took 0.10994076728820801 seconds
[0.64884627 0.10454667 0.24660707]
loop took 0.14054107666015625 seconds
[0.87434626 0.06246727 0.06318651]
loop took 0.22379183769226074 seconds
[0.99125403 0.00565009 0.0030958 ]
loop took 0.209244966506958 seconds
[0.98967093 0.00396741 0.0063617 ]
loop took 0.250591039657

[0.45992538 0.01688372 0.5231909 ]
loop took 0.11893224716186523 seconds
[0.52302086 0.00398954 0.4729896 ]
loop took 0.1139378547668457 seconds
[0.47080067 0.00936427 0.5198351 ]
loop took 0.11793279647827148 seconds
[0.4028954  0.03543876 0.5616659 ]
loop took 0.125929594039917 seconds
[0.5830423  0.02139413 0.39556357]
loop took 0.14891505241394043 seconds
[0.18185    0.00752658 0.8106234 ]
loop took 0.23005104064941406 seconds
[0.51146436 0.06673786 0.4217978 ]
loop took 0.11693644523620605 seconds
[0.555852   0.01160184 0.4325461 ]
loop took 0.09794330596923828 seconds
[0.8067913  0.01200323 0.18120535]
loop took 0.19602608680725098 seconds
[0.8606603  0.00729851 0.13204116]
loop took 0.23288297653198242 seconds
[0.97135293 0.00494092 0.02370615]
loop took 0.23008465766906738 seconds
[0.98022115 0.00236372 0.01741517]
loop took 0.20294523239135742 seconds
[9.9056727e-01 3.6329700e-04 9.0694288e-03]
loop took 0.2164313793182373 seconds
[9.9358255e-01 3.7236110e-04 6.0450523e-03]
lo

loop took 0.22446918487548828 seconds
[0.8757406  0.00304282 0.12121651]
loop took 0.21689844131469727 seconds
[0.9572247  0.00101439 0.04176084]
loop took 0.2360515594482422 seconds
[0.9044174  0.00233658 0.09324606]
loop took 0.22916579246520996 seconds
[0.72175294 0.01822187 0.2600252 ]
loop took 0.11294841766357422 seconds
[0.35140327 0.01774326 0.6308534 ]
loop took 0.11630892753601074 seconds
[0.11850282 0.00650631 0.87499094]
loop took 0.20027613639831543 seconds
[0.08525314 0.01187443 0.90287244]
loop took 0.2171018123626709 seconds
[0.0461796  0.00687183 0.9469485 ]
loop took 0.23968243598937988 seconds
[0.3759734  0.02213649 0.60189015]
loop took 0.12140035629272461 seconds
[0.7304174 0.0046366 0.264946 ]
loop took 0.1109318733215332 seconds
[0.7557865  0.00832125 0.23589228]
loop took 0.2166118621826172 seconds
[0.86397874 0.00475457 0.13126677]
loop took 0.21523404121398926 seconds
[0.96966684 0.00113101 0.02920222]
loop took 0.2368640899658203 seconds
[0.6370746  0.0058021

loop took 0.16490721702575684 seconds
[0.9713144  0.01677625 0.01190947]
loop took 0.3268139362335205 seconds
[0.97444195 0.01382198 0.01173609]
loop took 0.2884211540222168 seconds
[0.8786681  0.07232312 0.04900866]
loop took 0.2558562755584717 seconds
[0.00316066 0.00233514 0.9945042 ]
loop took 0.27983951568603516 seconds
[3.877012e-04 1.249783e-03 9.983625e-01]
loop took 0.2720310688018799 seconds
[0.00219406 0.00979208 0.98801386]
loop took 0.26115942001342773 seconds
[0.00658599 0.02527284 0.96814114]
loop took 0.25707340240478516 seconds
[0.12391935 0.04173677 0.8343439 ]
loop took 0.30445241928100586 seconds
[0.6960776  0.06651583 0.23740654]
loop took 0.09695124626159668 seconds
[0.73825765 0.04558128 0.21616112]
loop took 0.15495014190673828 seconds
[0.93563855 0.00655401 0.0578074 ]
loop took 0.24611735343933105 seconds
[0.93212795 0.03470241 0.03316969]
loop took 0.2447967529296875 seconds
[0.80270904 0.11355367 0.08373728]
loop took 0.2705354690551758 seconds
[0.83889484 0

[0.53908074 0.00152657 0.45939267]
loop took 0.08496475219726562 seconds
[0.53908074 0.00152657 0.45939267]
loop took 0.08198308944702148 seconds
[0.53908074 0.00152657 0.45939267]
loop took 0.08011245727539062 seconds
[0.53908074 0.00152657 0.45939267]
loop took 0.06696391105651855 seconds
[0.53908074 0.00152657 0.45939267]
loop took 0.08114075660705566 seconds
[0.53908074 0.00152657 0.45939267]
loop took 0.08298659324645996 seconds
[0.53908074 0.00152657 0.45939267]
loop took 0.0849144458770752 seconds
[0.53908074 0.00152657 0.45939267]
loop took 0.06608438491821289 seconds
[0.53908074 0.00152657 0.45939267]
loop took 0.06796121597290039 seconds
[0.53908074 0.00152657 0.45939267]
loop took 0.08098363876342773 seconds
[0.53908074 0.00152657 0.45939267]
loop took 0.06600642204284668 seconds
[0.53908074 0.00152657 0.45939267]
loop took 0.06496381759643555 seconds
[0.53908074 0.00152657 0.45939267]
loop took 0.06682276725769043 seconds
[0.53908074 0.00152657 0.45939267]
loop took 0.08395

loop took 0.08514666557312012 seconds
[0.5337699  0.0017698  0.46446025]
loop took 0.08186197280883789 seconds
[0.5337699  0.0017698  0.46446025]
loop took 0.06396365165710449 seconds
[0.5337699  0.0017698  0.46446025]
loop took 0.06696271896362305 seconds
[0.5337699  0.0017698  0.46446025]
loop took 0.08101582527160645 seconds
[0.5337699  0.0017698  0.46446025]
loop took 0.08595156669616699 seconds
[0.5337699  0.0017698  0.46446025]
loop took 0.07695531845092773 seconds
[0.5337699  0.0017698  0.46446025]
loop took 0.08897161483764648 seconds
[0.5337699  0.0017698  0.46446025]
loop took 0.09248089790344238 seconds
[0.5337699  0.0017698  0.46446025]
loop took 0.06696319580078125 seconds
[0.5337699  0.0017698  0.46446025]
loop took 0.09494829177856445 seconds
[0.5337699  0.0017698  0.46446025]
loop took 0.10193467140197754 seconds
[0.5337699  0.0017698  0.46446025]
loop took 0.08189630508422852 seconds
[0.5337699  0.0017698  0.46446025]
loop took 0.08397912979125977 seconds
[0.5337699  0

[0.10337238 0.04227094 0.8543567 ]
loop took 0.21491050720214844 seconds
[0.01154272 0.00178415 0.9866731 ]
loop took 0.2688286304473877 seconds
[7.2394982e-03 8.4371673e-04 9.9191684e-01]
loop took 0.21799707412719727 seconds
[6.9252024e-03 2.5665830e-04 9.9281812e-01]
loop took 0.19451665878295898 seconds
[0.7552704  0.00211493 0.24261464]
loop took 0.23096823692321777 seconds
[0.97444975 0.00306679 0.0224834 ]
loop took 0.22701334953308105 seconds
[0.9795847  0.00187495 0.01854032]
loop took 0.2683839797973633 seconds
[0.71480334 0.00813158 0.27706507]
loop took 0.13879013061523438 seconds
[0.20039293 0.01250419 0.7871029 ]
loop took 0.21346116065979004 seconds
[0.0201936  0.00770284 0.97210354]
loop took 0.23978734016418457 seconds
[0.03241843 0.04434026 0.92324126]
loop took 0.22258520126342773 seconds
[0.07603515 0.00706073 0.9169041 ]
loop took 0.23609471321105957 seconds
[4.9079627e-02 6.3092366e-04 9.5028949e-01]
loop took 0.22313642501831055 seconds
[2.7981754e-02 3.4432733e-

loop took 0.26085424423217773 seconds
[0.07261261 0.27422002 0.6531674 ]
loop took 0.16590523719787598 seconds
[0.15191598 0.12102225 0.7270618 ]
loop took 0.1740717887878418 seconds
[0.33784604 0.08367465 0.57847935]
loop took 0.17896699905395508 seconds
[0.47799578 0.01748828 0.5045159 ]
loop took 0.15890955924987793 seconds
[0.71066344 0.01678182 0.27255476]
loop took 0.1709003448486328 seconds
[0.92048824 0.00376631 0.07574549]
loop took 0.2684941291809082 seconds
[0.93477947 0.0032643  0.06195613]
loop took 0.2655951976776123 seconds
[0.61587924 0.10239266 0.28172812]
loop took 0.14291810989379883 seconds
[0.0594334  0.01853646 0.92203015]
loop took 0.23586630821228027 seconds
[0.08157686 0.00977    0.9086532 ]
loop took 0.26384401321411133 seconds
[0.01441699 0.02141487 0.96416813]
loop took 0.24485993385314941 seconds
[0.10102025 0.12456051 0.7744192 ]
loop took 0.23859786987304688 seconds
[0.37954184 0.10323796 0.5172202 ]
loop took 0.14211463928222656 seconds
[0.6481118  0.159

[0.37690574 0.0816403  0.5414539 ]
loop took 0.15091466903686523 seconds
[0.16682929 0.3258355  0.5073352 ]
loop took 0.15486359596252441 seconds
[0.04784371 0.7351072  0.21704915]
loop took 0.1639108657836914 seconds
[0.13417113 0.20060597 0.6652229 ]
loop took 0.15890860557556152 seconds
[0.1976628  0.15046796 0.65186924]
loop took 0.15091371536254883 seconds
[0.14278385 0.03837937 0.8188368 ]
loop took 0.24789094924926758 seconds
[0.22152337 0.02423211 0.7542445 ]
loop took 0.22188949584960938 seconds
[0.2620316  0.01095017 0.72701824]
loop took 0.14491796493530273 seconds
[0.5283548  0.05586123 0.415784  ]
loop took 0.16690611839294434 seconds
[0.38206577 0.04645312 0.5714811 ]
loop took 0.1818983554840088 seconds
[0.861378   0.08479463 0.0538274 ]
loop took 0.26895689964294434 seconds
[0.39539728 0.0281872  0.5764155 ]
loop took 0.17889857292175293 seconds
[0.08827776 0.00946932 0.9022529 ]
loop took 0.2538585662841797 seconds
[0.07948183 0.00540686 0.91511136]
loop took 0.2257902

[0.39086464 0.00263595 0.6064994 ]
loop took 0.12992620468139648 seconds
[0.37730703 0.00260315 0.6200899 ]
loop took 0.1479494571685791 seconds
[0.37244853 0.00272966 0.6248217 ]
loop took 0.13494110107421875 seconds
[0.35541168 0.00202233 0.642566  ]
loop took 0.1319286823272705 seconds
[0.33450872 0.00172242 0.6637689 ]
loop took 0.1339249610900879 seconds
[0.32858595 0.00214797 0.6692661 ]
loop took 0.15923810005187988 seconds
[0.29658797 0.00199399 0.701418  ]
loop took 0.16664886474609375 seconds
[0.32294166 0.00151786 0.6755405 ]
loop took 0.15691161155700684 seconds
[0.3171003  0.00168025 0.6812194 ]
loop took 0.14691662788391113 seconds
[0.3609452 0.0013726 0.6376822]
loop took 0.16190767288208008 seconds
[0.345066   0.00144454 0.6534894 ]
loop took 0.13292598724365234 seconds
[0.39338976 0.00141414 0.60519606]
loop took 0.14890694618225098 seconds
[0.28754398 0.00216964 0.7102864 ]
loop took 0.16475296020507812 seconds
[0.4210645  0.00187382 0.5770617 ]
loop took 0.1659049987

[0.6908074  0.03508256 0.2741101 ]
loop took 0.14891624450683594 seconds
[0.5614923  0.03145166 0.40705594]
loop took 0.1334381103515625 seconds
[0.74388236 0.02241259 0.23370507]
loop took 0.19588780403137207 seconds
[0.8227717  0.0162861  0.16094209]
loop took 0.22608470916748047 seconds
[0.93197083 0.01805072 0.04997851]
loop took 0.22139692306518555 seconds
[0.6261892  0.0235043  0.35030654]
loop took 0.16690587997436523 seconds
[0.76766783 0.00493709 0.22739503]
loop took 0.23378396034240723 seconds
[0.8330465  0.00388922 0.16306432]
loop took 0.27741527557373047 seconds
[0.7618346  0.00217138 0.23599404]
loop took 0.23648500442504883 seconds
[0.30906394 0.00305144 0.68788457]
loop took 0.17989754676818848 seconds
[7.0331499e-02 7.0995040e-04 9.2895854e-01]
loop took 0.26220011711120605 seconds
[1.6058780e-01 4.7996952e-04 8.3893228e-01]
loop took 0.23410820960998535 seconds
[0.1522803  0.00096234 0.8467574 ]
loop took 0.2379150390625 seconds
[0.11723194 0.00091679 0.8818512 ]
loo

[0.55781984 0.0416192  0.40056095]
loop took 0.17627406120300293 seconds
[0.17802909 0.00479076 0.8171801 ]
loop took 0.23310518264770508 seconds
[0.4204781  0.01660186 0.56292003]
loop took 0.1424422264099121 seconds
[0.6120754  0.01479606 0.37312853]
loop took 0.14891409873962402 seconds
[0.8361731  0.00628284 0.15754409]
loop took 0.25792670249938965 seconds
[0.38661516 0.00240063 0.61098415]
loop took 0.13591909408569336 seconds
[0.71849763 0.00445052 0.27705187]
loop took 0.2008981704711914 seconds
[0.58568436 0.00583822 0.40847743]
loop took 0.15990853309631348 seconds
[0.3220847  0.0035086  0.67440665]
loop took 0.14991307258605957 seconds
[0.13902059 0.00500769 0.8559717 ]
loop took 0.25527524948120117 seconds
[0.45275748 0.03118058 0.5160619 ]
loop took 0.14093255996704102 seconds
[0.3401512  0.00701959 0.6528293 ]
loop took 0.16890358924865723 seconds
[0.80979306 0.00457723 0.18562979]
loop took 0.3468494415283203 seconds
[0.82862085 0.03730399 0.13407518]
loop took 0.2612040

loop took 0.24687814712524414 seconds
[0.00973738 0.00223182 0.98803085]
loop took 0.2538268566131592 seconds
[0.01541189 0.01158057 0.9730075 ]
loop took 0.2268972396850586 seconds
[0.00814816 0.00271436 0.9891375 ]
loop took 0.22150158882141113 seconds
[0.01633698 0.00725977 0.9764032 ]
loop took 0.24782109260559082 seconds
[0.07242984 0.00785038 0.9197198 ]
loop took 0.2297365665435791 seconds
[0.09259275 0.01004436 0.89736295]
loop took 0.2608766555786133 seconds
[0.44652966 0.01255383 0.5409165 ]
loop took 0.13091802597045898 seconds
[0.35007787 0.02959058 0.6203315 ]
loop took 0.15091443061828613 seconds
[0.24131942 0.02277432 0.7359062 ]
loop took 0.12992644309997559 seconds
[0.49349305 0.01631309 0.49019384]
loop took 0.20088577270507812 seconds
[0.8778318  0.01192255 0.11024557]
loop took 0.22292065620422363 seconds
[0.6656876  0.01369388 0.32061848]
loop took 0.14393258094787598 seconds
[0.7293158  0.02780751 0.2428766 ]
loop took 0.15990805625915527 seconds
[0.6312884  0.019

loop took 0.21651434898376465 seconds
[0.88135034 0.0095532  0.10909645]
loop took 0.27185916900634766 seconds
[0.01458503 0.01386937 0.9715456 ]
loop took 0.21606659889221191 seconds
[0.00383824 0.01457348 0.98158824]
loop took 0.2588503360748291 seconds
[0.00302003 0.00511359 0.9918664 ]
loop took 0.2160472869873047 seconds
[0.001252   0.00503614 0.9937118 ]
loop took 0.26978468894958496 seconds
[0.02125754 0.0770883  0.9016542 ]
loop took 0.22290468215942383 seconds
[0.46976706 0.280273   0.24995984]
loop took 0.13492345809936523 seconds
[0.21643513 0.7558667  0.02769815]
loop took 0.14691543579101562 seconds
[0.12589957 0.85557705 0.01852328]
loop took 0.13193392753601074 seconds
[0.39345714 0.5941626  0.01238032]
loop took 0.1479032039642334 seconds
[0.70605683 0.28244847 0.01149471]
loop took 0.13325834274291992 seconds
[0.9409666  0.05002066 0.00901282]
loop took 0.24890422821044922 seconds
[0.92690736 0.06962172 0.00347094]
loop took 0.24837040901184082 seconds
[0.98090786 0.01